from __future__ import annotations

import sqlite3
from typing import Any, Protocol


class PersistencePort(Protocol):
    conn: sqlite3.Connection

    def migrate(self) -> None: ...
    def close(self) -> None: ...

    # Worlds
    def list_worlds(self) -> list[dict[str, Any]]: ...
    def get_world(self, world_id: str) -> dict[str, Any] | None: ...
    def insert_world(self, row: dict[str, Any]) -> None: ...
    def update_world(self, world_id: str, **fields: Any) -> None: ...
    def bump_event_seq(self, world_id: str) -> int: ...

    # Scenes
    def list_scenes(self, world_id: str) -> list[dict[str, Any]]: ...
    def get_scene(self, scene_id: str) -> dict[str, Any] | None: ...
    def insert_scene(self, row: dict[str, Any]) -> None: ...
    def update_scene(self, scene_id: str, **fields: Any) -> None: ...

    # Characters
    def insert_character(self, row: dict[str, Any]) -> None: ...
    def get_character(self, character_id: str) -> dict[str, Any] | None: ...
    def add_world_member(self, world_id: str, character_id: str, **kw: Any) -> None: ...
    def get_world_member(self, world_id: str, character_id: str) -> dict[str, Any] | None: ...
    def update_world_member(self, world_id: str, character_id: str, **fields: Any) -> None: ...
    def list_world_characters(self, world_id: str) -> list[dict[str, Any]]: ...

    # Messages
    def list_messages(
        self, world_id: str, *, scene_id: str | None = None, channel_kind: str = "scene"
    ) -> list[dict[str, Any]]: ...
    def insert_message(self, row: dict[str, Any]) -> None: ...
    def update_message(self, message_id: str, **fields: Any) -> None: ...

    # Loci / diary
    def upsert_locus(self, pool: str, owner_id: str, locus_key: str, value: str, updated_at: str) -> None: ...
    def search_loci(self, pool: str, owner_id: str, query: str, limit: int = 10) -> list[dict[str, Any]]: ...
    def append_diary(self, row: dict[str, Any]) -> None: ...
    def list_diary(self, character_id: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def search_diary(self, character_id: str, query: str, limit: int = 10) -> list[dict[str, Any]]: ...

    # Signals
    def list_signals(self, world_id: str, *, status: str | None = None) -> list[dict[str, Any]]: ...
    def insert_signal(self, row: dict[str, Any]) -> None: ...
    def update_signal(self, signal_id: str, **fields: Any) -> None: ...

    # Jobs
    def insert_job(self, row: dict[str, Any]) -> None: ...
    def get_job(self, job_id: str) -> dict[str, Any] | None: ...
    def update_job(self, job_id: str, **fields: Any) -> None: ...
    def list_queued_jobs(self, world_id: str) -> list[dict[str, Any]]: ...

    # Structures
    def list_structures(self, world_id: str) -> list[dict[str, Any]]: ...
    def insert_structure(self, row: dict[str, Any]) -> None: ...
